export { default as App } from "./App";
export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
export { default as Dashboard } from "./Dashboard";
export { default as UpdateProfile } from "./UpdateProfile";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as NavbarComponent } from "./NavbarComponent";
export { default as DeviceDetails } from "./DeviceDetails";
export { default as LandingPage } from "./LandingPage";
